### PR TITLE
gracc-reporting 2.0

### PR DESCRIPTION
**Pull request by shreyb**
This is the PR for gracc-reporting 2.0.  The main features of this release are:

1)  The reports themselves have been removed from this repository.  They are now hosted in the github repo gracc-osg-reports and fife-reports (managed at Fermilab - not hosted on github any longer).
2)  A number of unit tests have been added
3)  Changed packaging mechanism.  We'll now do deployments purely by docker image (hosted on the osg official dockerhub).

### CODE REVIEW

**Comment by shreyb** [comment]
3 notes:

1)  We'll want to change the repo description to note that these are libraries on which reports are built.
2)  This is already deployed in production
3)  TODO:  Dev docs will follow soon, but a new release won't be cut for just that.

**Comment by djw8605** [comment]
@shreyb could you resolve the conflicting configuration file.

**Comment by shreyb** [comment]
Yep - I'll take care of that sometime today if possible.

**Comment by shreyb** [comment]
Resolved and merged.  Should we go ahead and cut the new release?

**Pull request merged**
