### PR TITLE
Ignore local batch records

### PR DESCRIPTION
**Pull request by brianhlin**
We don't care about local user jobs

### CODE REVIEW

**Review by djw8605 — APPROVED** [review]
LGTM

**Comment by shreyb** [comment]
Well, this is awkward.  This is actually the wrong repo to make this change in.  I'm working on the dev docs that would have said so, but they aren't in here yet, which is my bad.  This repository will become just the underlying library for all reports (the currently deployed version actually uses that scheme), and the reports live in the gracc-osg-reports repo referenced below.  All that's keeping me from changing this repo is those dev docs, so perhaps I should put in the pull request to update this repo before anyone else makes more changes here due to bad information (again, my fault on that).

If you make the same changes to https://github.com/opensciencegrid/gracc-osg-reports, that'll be the right place, and we can get those into the report.

Thanks,
Shreyas

**Comment by shreyb** [comment]
Now that I think about it - let's do that.  @brianhlin - are you OK with making the changes in the other repo?  Once you and @djw8605 have done so, I'll open a PR to pull my changes (for gracc-reporting 2.0) in, cut the release, and then add the docs as I have time so they're at least a part of the repo, if not an official new release.

Does that sound good?

**Review by shreyb — CHANGES_REQUESTED** [review]
Please move these changes to https://github.com/opensciencegrid/gracc-osg-reports

**Comment by brianhlin** [comment]
Closing in favor of https://github.com/opensciencegrid/gracc-osg-reports/pull/6

**Pull request closed without merging**
