### PR TITLE
Dev docs

### PR DESCRIPTION
**Pull request by shreyb**
A hastily-compiiled developer document, along with a quick sample report I wrote that does (nearly) the bare minimum.

### CODE REVIEW

**Comment by shreyb** [comment]
Another note - after this, I'll go ahead and cut gracc-reporting 2.0 if you guys are good with it.  I haven't changed any of the code from when we deployed in production, just added this doc and a sample report/config file to go with it.  In the (hopefully near) future, I'll add a similar dev doc to gracc-osg-reports.

**Comment by shreyb** [comment]
@zvada @brianhlin Any comments on the docs?

**Comment by zvada** [comment]
At first glance, it looks good to me. I'm tempted to merge as is and go from there since this is initial doc anyway. @brianhlin, any objections to merging?

**Review by brianhlin — APPROVED** [review]
I had high hopes that I'd have time to read this over thoroughly but that certainly didn't happen. Since it's internal documentation and I don't have any objections after a quick glance, I'm on board with Marian's suggestion of just merging it.

**Comment by shreyb** [comment]
Thanks guys.  gracc-reporting 2.0 is out the door.

**Pull request merged**
