### PR TITLE
Adding CSIU in order to add Splinter project

### PR DESCRIPTION
**Pull request by djw8605**

### CODE REVIEW

**Comment by shreyb** [comment]
Looks good.

**Comment by shreyb** [comment]
Will Marian be doing this, or will I need to log in to put that in the config file that's deployed now?

**Comment by djw8605** [comment]
@zvada should do it.  Is it still living in your home directory?  What did we ever figure out?

**Comment by shreyb** [comment]
Yeah - it's in my home directory at gracc-reporting/config, but on
hcc-grace.unl.edu, which I guess is the old GRACC FE.

**Pull request merged**
